-- KickStock · Migration 009 · Username Persistence
--
-- Goal: the pseudo chosen by a player (guest or registered) must never change
-- across auth transitions (guest → email, guest → Google, email → Google same address).
--
-- Mechanism:
--   profiles.is_auto  TRUE  = username was auto-generated by the trigger
--                    FALSE = username was explicitly chosen by the player
--
-- Rules enforced by application + trigger:
--   • When a new user signs up via email with a pseudo in metadata → is_auto = FALSE
--   • When a new user signs up via Google (no pseudo) → is_auto = TRUE (generated)
--   • When a guest migrates to a registered account → callback carries guest_username
--     into profiles.username + sets is_auto = FALSE (only if profile was is_auto=TRUE)
--   • When a player explicitly sets a username → is_auto = FALSE

-- ── 1. Add is_auto column ──────────────────────────────────────────────────────
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS is_auto BOOLEAN NOT NULL DEFAULT TRUE;

-- ── 2. Backfill existing rows ──────────────────────────────────────────────────
-- Auto-generated usernames end with _[0-9a-f]{8} (8-char hex suffix from UUID).
-- Any profile that does NOT match this pattern already has a user-chosen pseudo.
UPDATE profiles
SET    is_auto = FALSE
WHERE  username !~ '_[0-9a-f]{8}$';

-- ── 3. Handle the specific user whose username is still auto-generated ─────────
-- (Optional — run only if the player already chose 'IchaboldTest2' via WelcomeModal
--  but it didn't save. Update their username manually here.)
-- UPDATE profiles SET username = 'IchaboldTest2', is_auto = FALSE
-- WHERE  username = 'ichabold_056e71be';

-- ── 4. Updated handle_new_user trigger ────────────────────────────────────────
--
-- Key change: if raw_user_meta_data contains a valid 'username', use it as-is
-- and mark is_auto = FALSE.  Otherwise generate the UUID-suffixed fallback.
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_username TEXT;
  v_is_auto  BOOLEAN;
BEGIN
  -- Email signup passes { username: '<pseudo>' } in options.data
  IF (NEW.raw_user_meta_data->>'username') IS NOT NULL
     AND length(trim(COALESCE(NEW.raw_user_meta_data->>'username', ''))) >= 3
  THEN
    v_username := trim(NEW.raw_user_meta_data->>'username');
    v_is_auto  := FALSE;
  ELSE
    -- Fallback: derive from email local-part + 8-char UUID hex (guaranteed unique)
    v_username := COALESCE(
      NULLIF(
        left(lower(regexp_replace(
          split_part(COALESCE(NEW.email, ''), '@', 1),
          '[^a-z0-9_]', '_', 'g'
        )), 12),
        ''
      ),
      'user'
    ) || '_' || substr(replace(NEW.id::TEXT, '-', ''), 1, 8);
    v_is_auto := TRUE;
  END IF;

  INSERT INTO profiles (id, username, is_auto)
    VALUES (NEW.id, v_username, v_is_auto)
    ON CONFLICT (id) DO NOTHING;

  INSERT INTO portfolios (user_id, cash)
    VALUES (NEW.id, 10000)
    ON CONFLICT (user_id) DO NOTHING;

  RETURN NEW;
END;
$$;

-- ── 5. Updated migrate_guest_to_user RPC ──────────────────────────────────────
--
-- Change: the JSONB result now always includes 'guest_username' so the callback
-- route can propagate it to profiles.username (only if is_auto=TRUE there).
-- No change to the core migration logic.
CREATE OR REPLACE FUNCTION migrate_guest_to_user(
  p_device_id TEXT,
  p_user_id   UUID
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_guest_id         UUID;
  v_guest_best       NUMERIC;
  v_guest_username   TEXT;
  v_user_id_existing UUID;
  v_user_best        NUMERIC;
BEGIN
  -- Find guest portfolio (must be unlinked to any user)
  SELECT id, best_score, guest_username
  INTO   v_guest_id, v_guest_best, v_guest_username
  FROM   portfolios
  WHERE  device_id = p_device_id
    AND  user_id IS NULL
  LIMIT  1;

  IF v_guest_id IS NULL THEN
    RETURN jsonb_build_object('status', 'no_guest');
  END IF;

  -- Check if this user already has a portfolio from another device
  SELECT id, best_score
  INTO   v_user_id_existing, v_user_best
  FROM   portfolios
  WHERE  user_id = p_user_id
  LIMIT  1;

  -- ── Simple case: no existing user portfolio ──────────────────────────────────
  IF v_user_id_existing IS NULL THEN
    UPDATE portfolios
    SET    user_id   = p_user_id,
           device_id = p_device_id
    WHERE  id = v_guest_id;

    RETURN jsonb_build_object(
      'status',         'migrated',
      'guest_username', v_guest_username
    );
  END IF;

  -- ── Conflict: two portfolios exist ───────────────────────────────────────────
  IF COALESCE(v_guest_best, 0) > COALESCE(v_user_best, 0) THEN
    -- Guest wins: delete old user portfolio, promote guest to user account
    DELETE FROM portfolios WHERE id = v_user_id_existing;
    UPDATE portfolios
    SET    user_id   = p_user_id,
           device_id = p_device_id
    WHERE  id = v_guest_id;

    RETURN jsonb_build_object(
      'status',         'conflict_resolved',
      'kept',           'guest',
      'guest_username', v_guest_username
    );
  ELSE
    -- User portfolio wins: orphan the guest portfolio
    UPDATE portfolios SET device_id = NULL WHERE id = v_guest_id;

    RETURN jsonb_build_object(
      'status', 'conflict_resolved',
      'kept',   'user'
    );
  END IF;
END;
$$;
