export { applyResult } from './applyResult';
export { simulate } from './simulate';
export { calcTax } from './calcTax';
export { calcDividend } from './calcDividends';
export { isMarketLocked } from './isMarketLocked';
export { initState, pctOf, fmt } from './initState';
export { buildR32Pool, buildMatchesForDay, deriveGroupStandings, buildGroupStandingsUI } from './buildKOMatches';
export type { StandingRow } from './buildKOMatches';
export { genScore } from './genScore';
export { genGoals } from './genGoals';
