-- KickStock · Seed · 48 Nations
-- Run AFTER 001_schema.sql

INSERT INTO nations (id, name, flag, initial_price, conf, str, grp) VALUES
  ('MEX','Mexico',       '🇲🇽', 25,  'CONCACAF', 72, 'A'),
  ('RSA','S. Africa',    '🇿🇦', 10,  'CAF',      49, 'A'),
  ('KOR','South Korea',  '🇰🇷', 20,  'AFC',      63, 'A'),
  ('CZE','Czechia',      '🇨🇿', 20,  'UEFA',     61, 'A'),
  ('CAN','Canada',       '🇨🇦', 25,  'CONCACAF', 68, 'B'),
  ('BIH','Bosnia',       '🇧🇦', 20,  'UEFA',     58, 'B'),
  ('QAT','Qatar',        '🇶🇦', 10,  'AFC',      48, 'B'),
  ('SUI','Switzerland',  '🇨🇭', 25,  'UEFA',     70, 'B'),
  ('BRA','Brazil',       '🇧🇷', 200, 'CONMEBOL', 88, 'C'),
  ('MAR','Morocco',      '🇲🇦', 20,  'CAF',      66, 'C'),
  ('HAI','Haiti',        '🇭🇹', 10,  'CONCACAF', 42, 'C'),
  ('SCO','Scotland',     '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 20,  'UEFA',     60, 'C'),
  ('USA','USA',          '🇺🇸', 50,  'CONCACAF', 76, 'D'),
  ('PAR','Paraguay',     '🇵🇾', 20,  'CONMEBOL', 62, 'D'),
  ('AUS','Australia',    '🇦🇺', 20,  'AFC',      58, 'D'),
  ('TUR','Türkiye',      '🇹🇷', 20,  'UEFA',     66, 'D'),
  ('GER','Germany',      '🇩🇪', 100, 'UEFA',     84, 'E'),
  ('CUW','Curaçao',      '🇨🇼', 10,  'CONCACAF', 40, 'E'),
  ('CIV','Ivory Coast',  '🇨🇮', 20,  'CAF',      60, 'E'),
  ('ECU','Ecuador',      '🇪🇨', 25,  'CONMEBOL', 65, 'E'),
  ('NED','Netherlands',  '🇳🇱', 75,  'UEFA',     82, 'F'),
  ('JPN','Japan',        '🇯🇵', 25,  'AFC',      68, 'F'),
  ('SWE','Sweden',       '🇸🇪', 20,  'UEFA',     64, 'F'),
  ('TUN','Tunisia',      '🇹🇳', 20,  'CAF',      55, 'F'),
  ('BEL','Belgium',      '🇧🇪', 50,  'UEFA',     80, 'G'),
  ('EGY','Egypt',        '🇪🇬', 20,  'CAF',      58, 'G'),
  ('IRN','Iran',         '🇮🇷', 20,  'AFC',      56, 'G'),
  ('NZL','New Zealand',  '🇳🇿', 10,  'OFC',      44, 'G'),
  ('ESP','Spain',        '🇪🇸', 200, 'UEFA',     92, 'H'),
  ('CPV','Cape Verde',   '🇨🇻', 10,  'CAF',      48, 'H'),
  ('KSA','Saudi Arabia', '🇸🇦', 10,  'AFC',      52, 'H'),
  ('URU','Uruguay',      '🇺🇾', 35,  'CONMEBOL', 74, 'H'),
  ('FRA','France',       '🇫🇷', 200, 'UEFA',     93, 'I'),
  ('SEN','Senegal',      '🇸🇳', 25,  'CAF',      68, 'I'),
  ('NOR','Norway',       '🇳🇴', 25,  'UEFA',     69, 'I'),
  ('IRQ','Iraq',         '🇮🇶', 10,  'AFC',      46, 'I'),
  ('ARG','Argentina',    '🇦🇷', 200, 'CONMEBOL', 91, 'J'),
  ('ALG','Algeria',      '🇩🇿', 20,  'CAF',      57, 'J'),
  ('AUT','Austria',      '🇦🇹', 20,  'UEFA',     62, 'J'),
  ('JOR','Jordan',       '🇯🇴', 10,  'AFC',      46, 'J'),
  ('POR','Portugal',     '🇵🇹', 100, 'UEFA',     86, 'K'),
  ('COD','DR Congo',     '🇨🇩', 10,  'CAF',      48, 'K'),
  ('UZB','Uzbekistan',   '🇺🇿', 10,  'AFC',      44, 'K'),
  ('COL','Colombia',     '🇨🇴', 25,  'CONMEBOL', 70, 'K'),
  ('ENG','England',      '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 200, 'UEFA',     90, 'L'),
  ('CRO','Croatia',      '🇭🇷', 35,  'UEFA',     74, 'L'),
  ('GHA','Ghana',        '🇬🇭', 20,  'CAF',      57, 'L'),
  ('PAN','Panama',       '🇵🇦', 20,  'CONCACAF', 53, 'L')
ON CONFLICT (id) DO NOTHING;
